.SILENT:

default: 
	gcc -Wall -Wextra lab1a.c -o lab1a


debug: 
	gcc -Wall -Wextra -g lab1a.c -o lab1a

dist: 
	tar -czf lab1a-904474415.tar.gz lab1a.c Makefile README

clean: 
	rm -f *.tar.gz lab1a
